// <auto-generated />
using System;
using ApiConciertos.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiConciertos.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260219140634_MiPrimeraChamba")]
    partial class MiPrimeraChamba
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiConciertos.Models.Eventos", b =>
                {
                    b.Property<Guid>("id_evento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("artista")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fecha_evento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("isActive")
                        .HasColumnType("int");

                    b.Property<string>("nombre_evento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id_evento");

                    b.ToTable("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
